FROM amd64/ubuntu:18.04
RUN apt-get update && apt-get install wget liblua5.1-dev -y
ENV aqtionversion=v0.5.3

# Download and install prebuild binaries
RUN mkdir /aq2server
RUN wget https://github.com/actionquake/distrib/releases/download/${aqtionversion}/aqtion-server-${aqtionversion}-linux-amd64.tar.gz && tar xfz aqtion-server-${aqtionversion}-linux-amd64.tar.gz -C /aq2server --strip-components=1

# Create user and add rights to aq2server
RUN useradd -rm -d /home/quake2 -s /bin/bash -g root -G sudo -u 1001 quake2

USER quake2
WORKDIR /aq2server

# Game var replacement begin


# Game vr replacement end

ENTRYPOINT ["start-server.sh"]
