on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag (ex: v1.2.3)"
        required: true

name: Butler (Itch.io) Release

env:
  CFG_WORKING_DIR: "config"
  LIN64_DIST_DIR: "linux-x64-dist"
  LINARM64_DIST_DIR: "linux-arm64-dist"
  WIN64_DIST_DIR: "windows-x64-dist"
  MAC_DIST_DIR: "mac-universal-dist"

jobs:      
  butler_release:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
          
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Install Butler (Itch.io)
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
          chmod +x butler
          ./butler -V

      # - name: Generate checksum file
      #   working-directory: ${{ env.CFG_WORKING_DIR }}/action
      #   run: |
      #     find -type f \( -not -name "checksums" \) -exec md5sum '{}' \; > checksums

      ## Linux x86_64
      - name: Download Linux release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-linux-x86_64
          skip_unpack: true

      ## Linux ARM64
      - name: Download Linux release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-linux-arm64
          skip_unpack: true

      ## Windows x86_64
      - name: Download Windows release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-windows-x86_64
          skip_unpack: true

      ## Mac
      - name: Download Mac release package
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          workflow: New-Dist-Release.yaml
          name: aqtion-${{ inputs.release_tag }}-mac-universal
          skip_unpack: true

      - name: Butler Push Win64
        run: ./butler push aqtion-${{ github.event.inputs.release_tag }}-windows-x86_64.zip aqtion/aqtion:windows-x64 --userversion ${{ github.event.inputs.release_tag }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      
      - name: Butler Push Lin64 x86
        run: ./butler push aqtion-${{ github.event.inputs.release_tag }}-linux-x86_64.zip aqtion/aqtion:linux-x64 --userversion ${{ github.event.inputs.release_tag }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: Butler Push Lin64 ARM
        run: ./butler push aqtion-${{ github.event.inputs.release_tag }}-linux-arm64.zip aqtion/aqtion:linux-arm --userversion ${{ github.event.inputs.release_tag }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      
      - name: Butler Push Mac Universal
        run: ./butler push aqtion-${{ github.event.inputs.release_tag }}-mac-universal.zip aqtion/aqtion:mac-universal --userversion ${{ github.event.inputs.release_tag }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      - name: 'Post-build cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./