name: Linux TNG (64-bit)

on:
  push:
    branches: ci

# on:
#   workflow_dispatch:

jobs:
  linux_x86_64_build_tng:
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v3
        with:
          # repository: aq2-tng/aq2-tng  ## Official repository
          repository: actionquake/aq2-tng
          ref: 'bots'
          path: build

      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: config
      
      - name: Get version info for tng
        id: version
        run: |
          cp config/build/getversion.sh build/
          cd build && bash -x getversion.sh tng >> versions

      - name: Build TNG
        working-directory: build/source
        run: make -j2 V=1 && mv gamex86_64.so ../gamex86_64.so
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-lin-x86_64-library
          path: |
            build/gamex86_64.so
            build/versions

  linux_arm64_build_tng:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aq2-tng/aq2-tng
          ref: 'bots'
          path: build

      - uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: config

      - name: Get version info for tng
        id: version
        run: |
          cp config/build/getversion.sh build/
          cd build && bash -x getversion.sh tng >> versions

      - name: Build TNG
        working-directory: build/source
        run: make -j2 V=1 && mv gameaarch64.so ../gameaarch64.so
        env:
          CC: "gcc"

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: tng-lin-arm64-library
          path: |
            build/gameaarch64.so
            build/versions